## Install Libraries

In [1]:
!pip install requests beautifulsoup4 pandas

Requirement already satisfied: requests in c:\users\trapti chauhan\anaconda\lib\site-packages (2.32.3)
Requirement already satisfied: beautifulsoup4 in c:\users\trapti chauhan\anaconda\lib\site-packages (4.12.3)
Requirement already satisfied: pandas in c:\users\trapti chauhan\anaconda\lib\site-packages (2.2.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\trapti chauhan\anaconda\lib\site-packages (from requests) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\trapti chauhan\anaconda\lib\site-packages (from requests) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\trapti chauhan\anaconda\lib\site-packages (from requests) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\trapti chauhan\anaconda\lib\site-packages (from requests) (2025.4.26)
Requirement already satisfied: soupsieve>1.2 in c:\users\trapti chauhan\anaconda\lib\site-packages (from beautifulsoup4) (2.5)
Requirement already satisfied: numpy>=1.26.0 in c:\users\trapti chauhan\anaconda\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\trapti chauhan\anaconda\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\trapti chauhan\anaconda\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\trapti chauhan\anaconda\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\trapti chauhan\anaconda\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

## Import Libraries

In [2]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [3]:
url = "https://books.toscrape.com/"
response = requests.get(url)
print(response.status_code)

200

In [4]:
print(response.text[:500])

<!DOCTYPE html>
<!--[if lt IE 7]>      <html lang="en-us" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html lang="en-us" class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html lang="en-us" class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html lang="en-us" class="no-js"> <!--<![endif]-->
    <head>
        <title>
    All products | Books to Scrape - Sandbox
</title>

        <meta http-equiv="content-type" content="text/html; charset=UTF-8" /

## Convert HTML into a Searchable Object

In [5]:
soup = BeautifulSoup(response.text, "html.parser")

In [6]:
books = soup.find_all("article", class_="product_pod")

print(len(books))

20

## Look at the First Book

In [7]:
books[0]

<article class="product_pod">
<div class="image_container">
<a href="catalogue/a-light-in-the-attic_1000/index.html"><img alt="A Light in the Attic" class="thumbnail" src="media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg"/></a>
</div>
<p class="star-rating Three">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/a-light-in-the-attic_1000/index.html" title="A Light in the Attic">A Light in the ...</a></h3>
<div class="product_price">
<p class="price_color">Â£51.77</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>

In [8]:
title = books[0].h3.a["title"]
print(title)

A Light in the Attic

## Extract the Price

In [9]:
price = books[0].find("p", class_="price_color").text
print(price)

Â£51.77

## Extract the Rating

In [10]:
rating = books[0].find("p")["class"][1]
print(rating)

Three

## Extract Availability

In [11]:
availability = books[0].find("p", class_="instock availability").text.strip()
print(availability)

In stock

## Extract the Product URL

In [12]:
link = books[0].h3.a["href"]
print(link)
product_url = "https://books.toscrape.com/" + link
print(product_url)

catalogue/a-light-in-the-attic_1000/index.html
https://books.toscrape.com/catalogue/a-light-in-the-attic_1000/index.html

## Print Everything Together

In [13]:
print("Title:", title)
print("Price:", price)
print("Rating:", rating)
print("Availability:", availability)
print("Product URL:", product_url)

Title: A Light in the Attic
Price: Â£51.77
Rating: Three
Availability: In stock
Product URL: https://books.toscrape.com/catalogue/a-light-in-the-attic_1000/index.html

## Create an Empty List

In [14]:
book_data =[]

## Scrap All 20 Books

In [15]:
book_data = []

for book in books:

    title = book.h3.a["title"]

    price = book.find("p", class_="price_color").text

    rating = book.find("p")["class"][1]

    availability = book.find("p", class_="instock availability").text.strip()

    link = book.h3.a["href"]
    product_url = "https://books.toscrape.com/" + link

    book_data.append({
        "Title": title,
        "Price": price,
        "Rating": rating,
        "Availability": availability,
        "Product URL": product_url
    })

## Check the Data

In [16]:
book_data

[{'Title': 'A Light in the Attic',
  'Price': 'Â£51.77',
  'Rating': 'Three',
  'Availability': 'In stock',
  'Product URL': 'https://books.toscrape.com/catalogue/a-light-in-the-attic_1000/index.html'},
 {'Title': 'Tipping the Velvet',
  'Price': 'Â£53.74',
  'Rating': 'One',
  'Availability': 'In stock',
  'Product URL': 'https://books.toscrape.com/catalogue/tipping-the-velvet_999/index.html'},
 {'Title': 'Soumission',
  'Price': 'Â£50.10',
  'Rating': 'One',
  'Availability': 'In stock',
  'Product URL': 'https://books.toscrape.com/catalogue/soumission_998/index.html'},
 {'Title': 'Sharp Objects',
  'Price': 'Â£47.82',
  'Rating': 'Four',
  'Availability': 'In stock',
  'Product URL': 'https://books.toscrape.com/catalogue/sharp-objects_997/index.html'},
 {'Title': 'Sapiens: A Brief History of Humankind',
  'Price': 'Â£54.23',
  'Rating': 'Five',
  'Availability': 'In stock',
  'Product URL': 'https://books.toscrape.com/catalogue/sapiens-a-brief-history-of-humankind_996/index.html'},
 {'Title': 'The Requiem Red',
  'Price': 'Â£22.65',
  'Rating': 'One',
  'Availability': 'In stock',
  'Product URL': 'https://books.toscrape.com/catalogue/the-requiem-red_995/index.html'},
 {'Title': 'The Dirty Little Secrets of Getting Your Dream Job',
  'Price': 'Â£33.34',
  'Rating': 'Four',
  'Availability': 'In stock',
  'Product URL': 'https://books.toscrape.com/catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html'},
 {'Title': 'The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull',
  'Price': 'Â£17.93',
  'Rating': 'Three',
  'Availability': 'In stock',
  'Product URL': 'https://books.toscrape.com/catalogue/the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html'},
 {'Title': 'The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics',
  'Price': 'Â£22.60',
  'Rating': 'Four',
  'Availability': 'In stock',
  'Product URL': 'https://books.toscrape.com/catalogue/the-boys-in-the-boat-nine-americans-and-their-epic-quest-for-gold-at-the-1936-berlin-olympics_992/index.html'},
 {'Title': 'The Black Maria',
  'Price': 'Â£52.15',
  'Rating': 'One',
  'Availability': 'In stock',
  'Product URL': 'https://books.toscrape.com/catalogue/the-black-maria_991/index.html'},
 {'Title': 'Starving Hearts (Triangular Trade Trilogy, #1)',
  'Price': 'Â£13.99',
  'Rating': 'Two',
  'Availability': 'In stock',
  'Product URL': 'https://books.toscrape.com/catalogue/starving-hearts-triangular-trade-trilogy-1_990/index.html'},
 {'Title': "Shakespeare's Sonnets",
  'Price': 'Â£20.66',
  'Rating': 'Four',
  'Availability': 'In stock',
  'Product URL': 'https://books.toscrape.com/catalogue/shakespeares-sonnets_989/index.html'},
 {'Title': 'Set Me Free',
  'Price': 'Â£17.46',
  'Rating': 'Five',
  'Availability': 'In stock',
  'Product URL': 'https://books.toscrape.com/catalogue/set-me-free_988/index.html'},
 {'Title': "Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)",
  'Price': 'Â£52.29',
  'Rating': 'Five',
  'Availability': 'In stock',
  'Product URL': 'https://books.toscrape.com/catalogue/scott-pilgrims-precious-little-life-scott-pilgrim-1_987/index.html'},
 {'Title': 'Rip it Up and Start Again',
  'Price': 'Â£35.02',
  'Rating': 'Five',
  'Availability': 'In stock',
  'Product URL': 'https://books.toscrape.com/catalogue/rip-it-up-and-start-again_986/index.html'},
 {'Title': 'Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991',
  'Price': 'Â£57.25',
  'Rating': 'Three',
  'Availability': 'In stock',
  'Product URL': 'https://books.toscrape.com/catalogue/our-band-could-be-your-life-scenes-from-the-american-indie-underground-1981-1991_985/index.html'},
 {'Title': 'Olio',
  'Price': 'Â£23.88',
  'Rating': 'One',
  'Availability': 'In stock',
  'Product URL': 'https://books.toscrape.com/catalogue/olio_984/index.html'},
 {'Title': 'Mesaerion: The Best Science Fiction Stories 1800-1849',
  'Price': 'Â£37.59',
  'Rating': 'One',
  'Availability': 'In stock',
  'Product URL': 'https://books.toscrape.com/catalogue/mesaerion-the-best-science-fiction-stories-1800-1849_983/index.html'},
 {'Title': 'Libertarianism for Beginners',
  'Price': 'Â£51.33',
  'Rating': 'Two',
  'Availability': 'In stock',
  'Product URL': 'https://books.toscrape.com/catalogue/libertarianism-for-beginners_982/index.html'},
 {'Title': "It's Only the Himalayas",
  'Price': 'Â£45.17',
  'Rating': 'Two',
  'Availability': 'In stock',
  'Product URL': 'https://books.toscrape.com/catalogue/its-only-the-himalayas_981/index.html'}]

## Convert to a DataFrame

In [17]:
df = pd.DataFrame(book_data)
df

,Title,Price,Rating,Availability,Product URL
0,A Light in the Attic,Â£51.77,Three,In stock,https://books.toscrape.com/catalogue/a-light-i...
1,Tipping the Velvet,Â£53.74,One,In stock,https://books.toscrape.com/catalogue/tipping-t...
2,Soumission,Â£50.10,One,In stock,https://books.toscrape.com/catalogue/soumissio...
3,Sharp Objects,Â£47.82,Four,In stock,https://books.toscrape.com/catalogue/sharp-obj...
4,Sapiens: A Brief History of Humankind,Â£54.23,Five,In stock,https://books.toscrape.com/catalogue/sapiens-a...
5,The Requiem Red,Â£22.65,One,In stock,https://books.toscrape.com/catalogue/the-requi...
6,The Dirty Little Secrets of Getting Your Dream...,Â£33.34,Four,In stock,https://books.toscrape.com/catalogue/the-dirty...
7,The Coming Woman: A Novel Based on the Life of...,Â£17.93,Three,In stock,https://books.toscrape.com/catalogue/the-comin...
8,The Boys in the Boat: Nine Americans and Their...,Â£22.60,Four,In stock,https://books.toscrape.com/catalogue/the-boys-...
9,The Black Maria,Â£52.15,One,In stock,https://books.toscrape.com/catalogue/the-black...
10,"Starving Hearts (Triangular Trade Trilogy, #1)",Â£13.99,Two,In stock,https://books.toscrape.com/catalogue/starving-...
11,Shakespeare's Sonnets,Â£20.66,Four,In stock,https://books.toscrape.com/catalogue/shakespea...
12,Set Me Free,Â£17.46,Five,In stock,https://books.toscrape.com/catalogue/set-me-fr...
13,Scott Pilgrim's Precious Little Life (Scott Pi...,Â£52.29,Five,In stock,https://books.toscrape.com/catalogue/scott-pil...
14,Rip it Up and Start Again,Â£35.02,Five,In stock,https://books.toscrape.com/catalogue/rip-it-up...
15,Our Band Could Be Your Life: Scenes from the A...,Â£57.25,Three,In stock,https://books.toscrape.com/catalogue/our-band-...
16,Olio,Â£23.88,One,In stock,https://books.toscrape.com/catalogue/olio_984/...
17,Mesaerion: The Best Science Fiction Stories 18...,Â£37.59,One,In stock,https://books.toscrape.com/catalogue/mesaerion...
18,Libertarianism for Beginners,Â£51.33,Two,In stock,https://books.toscrape.com/catalogue/libertari...
19,It's Only the Himalayas,Â£45.17,Two,In stock,https://books.toscrape.com/catalogue/its-only-...

## Save It as a CSV File

In [18]:
df.to_csv("books.csv", index=False)
print("Dataset saved successfully!")

Dataset saved successfully!

## Scrap All 50 Books

In [19]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

book_data = []

BASE_URL = "https://books.toscrape.com/"

for page in range(1, 51):

    if page == 1:
        url = BASE_URL
    else:
        url = BASE_URL + f"catalogue/page-{page}.html"

    print(f"Scraping Page {page}...")

    response = requests.get(url)
    soup = BeautifulSoup(response.text, "html.parser")

    books = soup.find_all("article", class_="product_pod")

    for book in books:

        title = book.h3.a["title"]

        price = book.find("p", class_="price_color").text

        rating = book.find("p")["class"][1]

        availability = book.find(
            "p",
            class_="instock availability"
        ).text.strip()

        link = book.h3.a["href"]

        if page == 1:
            product_url = BASE_URL + link
        else:
            product_url = BASE_URL + "catalogue/" + link.replace("../", "")

        book_data.append({
            "Title": title,
            "Price": price,
            "Rating": rating,
            "Availability": availability,
            "Product URL": product_url
        })

print("Scraping Completed!")

Scraping Page 1...
Scraping Page 2...
Scraping Page 3...
Scraping Page 4...
Scraping Page 5...
Scraping Page 6...
Scraping Page 7...
Scraping Page 8...
Scraping Page 9...
Scraping Page 10...
Scraping Page 11...
Scraping Page 12...
Scraping Page 13...
Scraping Page 14...
Scraping Page 15...
Scraping Page 16...
Scraping Page 17...
Scraping Page 18...
Scraping Page 19...
Scraping Page 20...
Scraping Page 21...
Scraping Page 22...
Scraping Page 23...
Scraping Page 24...
Scraping Page 25...
Scraping Page 26...
Scraping Page 27...
Scraping Page 28...
Scraping Page 29...
Scraping Page 30...
Scraping Page 31...
Scraping Page 32...
Scraping Page 33...
Scraping Page 34...
Scraping Page 35...
Scraping Page 36...
Scraping Page 37...
Scraping Page 38...
Scraping Page 39...
Scraping Page 40...
Scraping Page 41...
Scraping Page 42...
Scraping Page 43...
Scraping Page 44...
Scraping Page 45...
Scraping Page 46...
Scraping Page 47...
Scraping Page 48...
Scraping Page 49...
Scraping Page 50...
Scraping Completed!

## Check the Number of Books

In [20]:
len(book_data)

1000

## Convert to DataFrame

In [21]:
df=pd.DataFrame(book_data)
df.head()

,Title,Price,Rating,Availability,Product URL
0,A Light in the Attic,Â£51.77,Three,In stock,https://books.toscrape.com/catalogue/a-light-i...
1,Tipping the Velvet,Â£53.74,One,In stock,https://books.toscrape.com/catalogue/tipping-t...
2,Soumission,Â£50.10,One,In stock,https://books.toscrape.com/catalogue/soumissio...
3,Sharp Objects,Â£47.82,Four,In stock,https://books.toscrape.com/catalogue/sharp-obj...
4,Sapiens: A Brief History of Humankind,Â£54.23,Five,In stock,https://books.toscrape.com/catalogue/sapiens-a...

## Check Dataset Information

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Title         1000 non-null   object
 1   Price         1000 non-null   object
 2   Rating        1000 non-null   object
 3   Availability  1000 non-null   object
 4   Product URL   1000 non-null   object
dtypes: object(5)
memory usage: 39.2+ KB

## Check for Missing Values

In [23]:
df.isnull().sum()

Title           0
Price           0
Rating          0
Availability    0
Product URL     0
dtype: int64

## Check Duplicate Values

In [24]:
df.duplicated().sum()

np.int64(0)

## Save the Dataset

In [25]:
df.to_csv("books.csv", index = False)
print("books.csv created successfully!")

books.csv created successfully!